### ISSUE TITLE
Missing neighborhoods

### ISSUE THREAD

**Issue by anastasia** [Unnamed-Lab-DUSP/utility_datasets#1]
- Roxbury Crossing
- Dorchester Center

all cities in filings here: https://docs.google.com/spreadsheets/d/1X5wGyg9efzT-uqC4EaTZiIHGREBiYRtbgZ2qxqAfFJU/edit#gid=1624895563

**Comment by ericrobskyhuntley** [comment]
Good call, but made this change in this repository instead of the project repo in 1efe398 (I'm writing `loader.R` to request CSV from this repo - see [`load_utility_file()`](https://github.com/Unnamed-Lab-DUSP/evicting_lawyers/blob/96bdce97d84d3bd345873b121a92669ea832bacd/scripts/loader.R#L127-L135) and [these global vars](https://github.com/Unnamed-Lab-DUSP/evicting_lawyers/blob/96bdce97d84d3bd345873b121a92669ea832bacd/scripts/loader.R#L6-L8).
